/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrace;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

public class Levels_Page extends javax.swing.JFrame
{
    int width = 815;
    int height = 680;
    int level;
    public Levels_Page() {
        initComponents();
        setSize(width, height);
        jPanel1.setSize(width, height);
        jLabel1.setSize(width, height);
        setTitle("Levels");
        centerWindow(this);
    }
    public void centerWindow(Component frame) {
        Dimension screenSize
                = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = frame.getSize();
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        frame.setLocation(
                (screenSize.width - frameSize.width) >> 1,
                (screenSize.height - frameSize.height) >> 1
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Level1_Btn = new javax.swing.JButton();
        Level3_Btn = new javax.swing.JButton();
        Level2_Btn = new javax.swing.JButton();
        Level4_Btn = new javax.swing.JButton();
        Level6_Btn = new javax.swing.JButton();
        Level5_Btn = new javax.swing.JButton();
        Level1_Label = new javax.swing.JLabel();
        Level2_Label = new javax.swing.JLabel();
        Level3_Label = new javax.swing.JLabel();
        Level4_Label = new javax.swing.JLabel();
        Level5_Label = new javax.swing.JLabel();
        Level6_Label = new javax.swing.JLabel();
        Select_Btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Level1_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Level1_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/level1.jpg"))); // NOI18N
        Level1_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level1_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level1_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Level1_Btn);
        Level1_Btn.setBounds(25, 30, 200, 200);

        Level3_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Level3_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/level3.jpg"))); // NOI18N
        Level3_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level3_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level3_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Level3_Btn);
        Level3_Btn.setBounds(580, 30, 200, 200);

        Level2_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Level2_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/level2.jpg"))); // NOI18N
        Level2_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level2_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level2_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Level2_Btn);
        Level2_Btn.setBounds(300, 30, 200, 200);

        Level4_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Level4_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/level4.jpg"))); // NOI18N
        Level4_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level4_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level4_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Level4_Btn);
        Level4_Btn.setBounds(25, 300, 200, 200);

        Level6_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Level6_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/level6.jpg"))); // NOI18N
        Level6_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level6_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level6_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Level6_Btn);
        Level6_Btn.setBounds(580, 300, 200, 200);

        Level5_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Level5_Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/level5.jpg"))); // NOI18N
        Level5_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Level5_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Level5_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Level5_Btn);
        Level5_Btn.setBounds(300, 300, 200, 200);

        Level1_Label.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        Level1_Label.setForeground(new java.awt.Color(0, 0, 0));
        Level1_Label.setText("ROAD WORK");
        jPanel1.add(Level1_Label);
        Level1_Label.setBounds(30, 240, 180, 40);

        Level2_Label.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        Level2_Label.setForeground(new java.awt.Color(0, 0, 0));
        Level2_Label.setText("BACK ON TRACK");
        jPanel1.add(Level2_Label);
        Level2_Label.setBounds(300, 240, 220, 40);

        Level3_Label.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        Level3_Label.setForeground(new java.awt.Color(0, 0, 0));
        Level3_Label.setText("DRIVEN TO WIN");
        jPanel1.add(Level3_Label);
        Level3_Label.setBounds(580, 240, 220, 40);

        Level4_Label.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        Level4_Label.setForeground(new java.awt.Color(0, 0, 0));
        Level4_Label.setText("THE SPOOKY SOUND");
        jPanel1.add(Level4_Label);
        Level4_Label.setBounds(0, 510, 270, 40);
        Level4_Label.getAccessibleContext().setAccessibleName("THE SPOOKY SOUND");

        Level5_Label.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        Level5_Label.setForeground(new java.awt.Color(0, 0, 0));
        Level5_Label.setText("FRIENDS TO THE FINISH");
        jPanel1.add(Level5_Label);
        Level5_Label.setBounds(270, 510, 300, 40);

        Level6_Label.setFont(new java.awt.Font("Curlz MT", 1, 24)); // NOI18N
        Level6_Label.setForeground(new java.awt.Color(0, 0, 0));
        Level6_Label.setText("YOU DARE ?");
        jPanel1.add(Level6_Label);
        Level6_Label.setBounds(590, 510, 180, 40);

        Select_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Select_Btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Select_Btn.setForeground(new java.awt.Color(225, 225, 225));
        Select_Btn.setText("SELECT");
        Select_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Select_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Select_Btn);
        Select_Btn.setBounds(190, 580, 140, 60);

        Back_Btn.setBackground(new java.awt.Color(0, 0, 0));
        Back_Btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Back");
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Btn);
        Back_Btn.setBounds(480, 580, 140, 60);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarRace.GUI/background_18.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 800, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Level1_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level1_BtnActionPerformed
        // TODO add your handling code here:
        level = 1;
        Level1_Label.setText("*ROAD WORK*");
        Level2_Label.setText("BACK ON TRACK");
        Level3_Label.setText("DRIVEN TO WIN");
        Level4_Label.setText("THE SPOOKY SOUND");
        Level5_Label.setText("FRIENDS TO THE FINISH");
        Level6_Label.setText("YOU DARE ?");
       
    }//GEN-LAST:event_Level1_BtnActionPerformed

    private void Level2_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level2_BtnActionPerformed
        // TODO add your handling code here:
        level = 2;
        Level1_Label.setText("ROAD WORK");
        Level2_Label.setText("*BACK ON TRACK*");
        Level3_Label.setText("DRIVEN TO WIN");
        Level4_Label.setText("THE SPOOKY SOUND");
        Level5_Label.setText("FRIENDS TO THE FINISH");
        Level6_Label.setText("YOU DARE ?");
    }//GEN-LAST:event_Level2_BtnActionPerformed

    private void Level3_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level3_BtnActionPerformed
        // TODO add your handling code here:
        level = 3;
        Level1_Label.setText("ROAD WORK");
        Level2_Label.setText("BACK ON TRACK");
        Level3_Label.setText("*DRIVEN TO WIN*");
        Level4_Label.setText("THE SPOOKY SOUND");
        Level5_Label.setText("FRIENDS TO THE FINISH");
        Level6_Label.setText("YOU DARE ?");
    }//GEN-LAST:event_Level3_BtnActionPerformed

    private void Level4_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level4_BtnActionPerformed
        // TODO add your handling code here:
        level = 4;
        Level1_Label.setText("ROAD WORK");
        Level2_Label.setText("BACK ON TRACK");
        Level3_Label.setText("DRIVEN TO WIN");
        Level4_Label.setText("*THE SPOOKY SOUND*");
        Level5_Label.setText("FRIENDS TO THE FINISH");
        Level6_Label.setText("YOU DARE ?");
    }//GEN-LAST:event_Level4_BtnActionPerformed

    private void Level5_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level5_BtnActionPerformed
        // TODO add your handling code here:
        level = 5;
        Level1_Label.setText("ROAD WORK");
        Level2_Label.setText("BACK ON TRACK");
        Level3_Label.setText("DRIVEN TO WIN");
        Level4_Label.setText("THE SPOOKY SOUND");
        Level5_Label.setText("*FRIENDS TO THE FINISH*");
        Level6_Label.setText("YOU DARE ?");
    }//GEN-LAST:event_Level5_BtnActionPerformed

    private void Level6_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Level6_BtnActionPerformed
        // TODO add your handling code here:
        level = 6;
        Level1_Label.setText("ROAD WORK");
        Level2_Label.setText("BACK ON TRACK");
        Level3_Label.setText("DRIVEN TO WIN");
        Level4_Label.setText("THE SPOOKY SOUND");
        Level5_Label.setText("FRIENDS TO THE FINISH");
        Level6_Label.setText("*YOU DARE ?*");
    }//GEN-LAST:event_Level6_BtnActionPerformed

    private void Select_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("You Selected Level " + level);
        if(level == 1)
        {
            //go to level 1 page
        }
        else if(level == 2)
        {
            //go to level 2 page
        }
        else if(level == 3)
        {
            //go to level 3 page
        }
        else if(level == 4)
        {
            //go to level 4 page
        }
        else if(level == 5)
        {
            //go to level 5 page
        }
        else if(level == 6)
        {
            //go to level 6 page
        }
    }//GEN-LAST:event_Select_BtnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        try {
            // TODO add your handling code here:
            Levels_Page.this.setVisible(false);
            Menu_Page menu_page = new Menu_Page();
            menu_page.setVisible(true);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Levels_Page.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Levels_Page.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Levels_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Back_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Levels_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Levels_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Levels_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Levels_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Levels_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton Level1_Btn;
    private javax.swing.JLabel Level1_Label;
    private javax.swing.JButton Level2_Btn;
    private javax.swing.JLabel Level2_Label;
    private javax.swing.JButton Level3_Btn;
    private javax.swing.JLabel Level3_Label;
    private javax.swing.JButton Level4_Btn;
    private javax.swing.JLabel Level4_Label;
    private javax.swing.JButton Level5_Btn;
    private javax.swing.JLabel Level5_Label;
    private javax.swing.JButton Level6_Btn;
    private javax.swing.JLabel Level6_Label;
    private javax.swing.JButton Select_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
